spring:
  cloud:
    config:
      enabled: false

  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://localhost:5432/ojosama_db}
    username: ${USER_DB_USERNAME:postgres}
    password: ${USER_DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:user-service-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ojosama.userservice.infrastructure.messaging.kafka.dto"

eureka:
  client:
    enabled: false

internal:
  api:
    token: ${INTERNAL_API_TOKEN:local-internal-token}

kafka:
  topic:
    user-blacklist-status: ${KAFKA_TOPIC_USER_BLACKLIST_STATUS:operation.blacklist.updated}