spring:
  application:
    name: favorite-service

  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    config:
      username: ${CONFIG_USERNAME}
      password: ${CONFIG_PASSWORD}