global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "chat-service"
    metrics_path: "/chat-service/actuator/prometheus"
    static_configs:
      - targets: [ "festie-alb-1266745276.ap-northeast-2.elb.amazonaws.com:80" ]

  - job_name: "gateway-server"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "festie-alb-1266745276.ap-northeast-2.elb.amazonaws.com:80" ]

  - job_name: "user-service"
    metrics_path: "/user-service/actuator/prometheus"
    static_configs:
      - targets: [ "festie-alb-1266745276.ap-northeast-2.elb.amazonaws.com:80" ]

  - job_name: "event-service"
    metrics_path: "/event-service/actuator/prometheus"
    static_configs:
      - targets: [ "festie-alb-1266745276.ap-northeast-2.elb.amazonaws.com:80" ]

  - job_name: "operation-service"
    metrics_path: "/operation-service/actuator/prometheus"
    static_configs:
      - targets: [ "festie-alb-1266745276.ap-northeast-2.elb.amazonaws.com:80" ]

  - job_name: "ai-service"
    metrics_path: "/ai-service/actuator/prometheus"
    static_configs:
      - targets: [ "festie-alb-1266745276.ap-northeast-2.elb.amazonaws.com:80" ]

  - job_name: "calendar-service"
    metrics_path: "/calendar-service/actuator/prometheus"
    static_configs:
      - targets: [ "festie-alb-1266745276.ap-northeast-2.elb.amazonaws.com:80" ]

  - job_name: "notification-service"
    metrics_path: "/notification-service/actuator/prometheus"
    static_configs:
      - targets: [ "festie-alb-1266745276.ap-northeast-2.elb.amazonaws.com:80" ]

  - job_name: "favorite-service"
    metrics_path: "/favorite-service/actuator/prometheus"
    static_configs:
      - targets: [ "festie-alb-1266745276.ap-northeast-2.elb.amazonaws.com:80" ]

  - job_name: "community-service"
    metrics_path: "/community-service/actuator/prometheus"
    static_configs:
      - targets: [ "festie-alb-1266745276.ap-northeast-2.elb.amazonaws.com:80" ]
