spring:
  application:
    name: config-server

  config:
    import: "optional:classpath:application-secret.yml"

  security:
    user:
      name: ${CONFIG_USERNAME}
      password: ${CONFIG_PASSWORD}

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_URL}
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: main
          ignoreLocalSshSettings: true

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health, refresh
  endpoint:
    health:
      show-details: when_authorized