spring:
  application:
    name: config-server

  config:
    import: "optional:classpath:application-secret.yml"

  security:
    user:
      name: ${CONFIG_USERNAME}
      password: ${CONFIG_PASSWORD}

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_URL}
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: main
          ignoreLocalSshSettings: true

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://festie-eureka:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name:unknown}
