### 생성

POST {{calendarUrl}}/v1/calendars
Content-Type: application/json
X-User-Id: 11111111-2222-1111-1111-111111111111


{
  "memo": "성공해라..!",
  "eventId": "231acb67-f066-4ec2-adbe-77b34a5b1fa4",
  "eventDate": "2026-05-03T10:00:00",
  "ticketingDate": "2026-05-30T20:00:00",
  "eventName": "꽃 축제"
}

#### ### 단건조회 (캘린더 uuid)

GET {{calendarUrl}}/v1/calendars/c6f8ee12-fa61-4ffc-a72c-662af22af9ea
Content-Type: application/json
X-User-Id: 11111111-2222-1111-1111-111111111111


#### ### 전체조회

GET {{calendarUrl}}/v1/calendars?year=2026&month=5
Content-Type: application/json
X-User-Id: 11111111-2222-1111-1111-111111111111


### **수정 (캘린더 uuid)**

PATCH {{calendarUrl}}/v1/calendars/c6f8ee12-fa61-4ffc-a72c-662af22af9ea
Content-Type: application/json
X-User-Id: 11111111-2222-1111-1111-111111111111

{
  "memo": "2명으로 변경"
}





#### 행사 임박 스케줄러

1분마다 → notification-service 생성 확인 (이메일 확인, 이메일로그 테이블 확인, 알림 테이블 확인)

#### 티켓팅 임박 스케줄러

1분마다 → notification-service 생성 확인 (이메일 확인, 이메일로그 테이블 확인, 알림 테이블 확인)

**생각해보니까.. 지금 … 메인 캘린더를 아직 못만들어서 이건 .. 오늘 끝나고 만들겠습니다.**

---

**카프카 확인**

event-service 변경 → calendar-service 변경 → notification-service 확인 

event-serivce 삭제 → calendar-service 삭제 → notification-service 확인