### Category Service Demo
### IntelliJ HTTP Client용

###카테고리 작성
POST {{communityUrl}}/v1/community-categories

Content-Type: application/json
{
"name":"테스트카테고리"
}

###카테고리 수정
PATCH {{communityUrl}}/v1/community-categories/{categoryId}

Content-Type: application/json
{

"name":"테스트카테고리이름변경"

}

###카테고리 삭제
DELETE {{communityUrl}}/v1/community-categories/{categoryId}

Content-Type: application/json
{

"name":"테스트카테고리이름변경"

}

###카테고리 목록조회
GET {{communityUrl}}/v1/community-categories?page=0&size=20
