### 카테고리 목록 조회
GET {{eventUrl}}/v1/event-categories
X-User-Id: 00000000-0000-0000-0000-000000000001

###

### 카테고리 등록
POST {{eventUrl}}/v1/event-categories
Content-Type: application/json
X-User-Id: 00000000-0000-0000-0000-000000000001

{
  "name": "CONCERT"
}

###

### 카테고리 수정
PATCH {{eventUrl}}/v1/event-categories/{{categoryId}}
Content-Type: application/json
X-User-Id: 00000000-0000-0000-0000-000000000001

{
  "name": "FESTIVAL"
}

###

### 카테고리 삭제
DELETE {{eventUrl}}/v1/event-categories/{{categoryId}}
X-User-Id: 00000000-0000-0000-0000-000000000001

###

### [Internal] 카테고리 단건 조회
GET {{eventUrl}}/internal/v1/event-categories/{{categoryId}}
