### favorite-service
@userId = e6ab78d7-74c4-4bcd-8851-afd7b95daa02
@eventId = a25ac0fd-cb7f-48e4-b31c-6f492fd597a5
@accessToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyYTQyNzM0Ni1kNTJjLTQxNTEtYTY4OC04YWUyZTQzNjIzNzkiLCJlbWFpbCI6Im9vam9zYW1hNUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsIm5pY2tuYW1lIjoiaG9obyIsInRva2VuVHlwZSI6IkFDQ0VTUyIsImlhdCI6MTc3ODY0MjM1NSwiZXhwIjoxNzc4NjQ1OTU1fQ.-quNzgveAEvUTaLk0-Ap4Srb1P603SUL1DDaS1LOErw
### **생성**

POST {{favoriteUrl}}/v1/favorites
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "eventId": "{{eventId}}",
  "categoryId": "8b54a7e0-cd7a-4ed8-b42d-6489dd4b0e2e"
}

###  **전체 조회**

GET {{favoriteUrl}}/v1/favorites
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### **삭제 ( 생성에서 생긴 uuid  )**

DELETE {{favoriteUrl}}/v1/favorites/50906657-7dec-49a2-88e3-61bd67283620
Content-Type: application/json
X-User-Id: {{userId}}



### **카프카**

### event-service 삭제 → favorite-service 삭제확인

### event-service 변경 → favorite-service  변경확인