### 포트 확인 후 baseUrl 수정

### **생성**

POST {{favoriteUrl}}/v1/favorites
Content-Type: application/json
X-User-Id: 11111111-2222-1111-1111-111111111111


{
  "eventId": "381f3064-112e-4de2-ac70-7b65999e0aeb",
  "categoryId": "8b54a7e0-cd7a-4ed8-b42d-6489dd4b0e2e"
}

###  **전체 조회**

GET {{favoriteUrl}}/v1/favorites
Content-Type: application/json
X-User-Id: 11111111-2222-1111-1111-111111111111

### **삭제 ( 생성에서 생긴 uuid  )**

DELETE {{favoriteUrl}}/v1/favorites/{favoriteId}
Content-Type: application/json
X-User-Id: 11111111-2222-1111-1111-111111111111



### **카프카**

### event-service 삭제 → favorite-service 삭제확인

### event-service 변경 → favorite-service  변경확인